export const STORES = [
  { code: "AZ105", name: "Yogurtland Onboarding Demo Vendor" },
  { code: "AZ104", name: "Yogurtland Silver Demo Vendor" },
  { code: "AZ103", name: "Yogurtland Brink Demo Vendor" },
  { code: "CA349", name: "YOGURTLAND AVONDALE" },
  { code: "CA348", name: "YOGURTLAND CHANDLER" },
  { code: "CA347", name: "YOGURTLAND MESA - DANA PARK" },
  { code: "CA346", name: "YOGURTLAND CUPERTINO" },
  { code: "CA345", name: "YOGURTLAND TUSTIN" },
  { code: "CA344", name: "YOGURTLAND CERRITOS MALL" },
  { code: "CA343", name: "YOGURTLAND LAGUNA HILLS" },
  { code: "CA342", name: "YOGURTLAND SHERMAN OAKS" },
  { code: "CA341", name: "YOGURTLAND HUNTINGTON BEACH" },
  { code: "CA340H", name: "YOGURTLAND SDSU" },
  { code: "CA339", name: "YOGURTLAND MIRACLE MILE" },
  { code: "CA338", name: "YOGURTLAND ARTESIA" },
  { code: "CA337", name: "YOGURTLAND COSTA MESA" },
  { code: "CA334", name: "YOGURTLAND UCI" },
  { code: "CA333", name: "YOGURTLAND FULLERTON DOWNTOWN" },
  { code: "CA332", name: "YOGURTLAND CHINO HILLS" },
  { code: "CA330", name: "YOGURTLAND ARCADIA" },
  { code: "CA329", name: "YOGURTLAND WEST COVINA" },
  { code: "CA328", name: "YOGURTLAND ANAHEIM HILLS" },
  { code: "CA327", name: "YOGURTLAND BREA" },
  { code: "CA326", name: "YOGURTLAND WESTGATE WEST" },
  { code: "CA325", name: "YOGURTLAND IRVINE" },
  { code: "CA324", name: "YOGURTLAND PLEASANT HILL" },
  { code: "CA323", name: "YOGURTLAND SANTA BARBARA" },
  { code: "CA322", name: "YOGURTLAND ANAHEIM" },
  { code: "CA321", name: "YOGURTLAND CULVER CITY" },
  { code: "CA318", name: "YOGURTLAND MIRA MESA" },
  { code: "CA317", name: "YOGURTLAND CLAREMONT" },
  { code: "CA316", name: "YOGURTLAND EVERGREEN VALLEY CENTER" },
  { code: "CA315", name: "YOGURTLAND RIVIERA PLACE" },
  { code: "CA314", name: "YOGURTLAND DANA POINT" },
  { code: "CA313", name: "YOGURTLAND DUBLIN WEST" },
  { code: "CA309", name: "YOGURTLAND MANHATTAN BEACH" },
  { code: "CA308", name: "YOGURTLAND LAKE FOREST" },
  { code: "CA306", name: "YOGURTLAND USC GATEWAY VILLAGE" },
  { code: "CA305", name: "YOGURTLAND RIVERSIDE CAMPUS" },
  { code: "CA304", name: "YOGURTLAND MILPITAS" },
  { code: "CA303", name: "YOGURTLAND RESEDA" },
  { code: "CA302", name: "YOGURTLAND PICO RIVERA" },
  { code: "CA301", name: "YOGURTLAND ENCINO" },
  { code: "CA300", name: "YOGURTLAND VILLAGE DEL AMO" },
  { code: "CA299", name: "YOGURTLAND LAKEWOOD" },
  { code: "CA298", name: "YOGURTLAND WESTLAKE VILLAGE" },
  { code: "CA297", name: "YOGURTLAND SIMI VALLEY" },
  { code: "CA296", name: "YOGURTLAND LA HABRA" },
  { code: "CA295", name: "YOGURTLAND ESCONDIDO" },
  { code: "CA294", name: "YOGURTLAND THE RIVER PARK AT FRESNO" },
  { code: "CA293", name: "YOGURTLAND WALNUT CREEK" },
  { code: "CA292", name: "YOGURTLAND CORONA" },
  { code: "CA291", name: "YOGURTLAND THE SHOPS AT ROSSMOOR" },
  { code: "CA290", name: "YOGURTLAND ATLANTIC SQUARE" },
  { code: "CA289", name: "YOGURTLAND STORY & KING ROAD" },
  { code: "CA288", name: "YOGURTLAND TARRAGONA PLAZA" },
  { code: "CA287", name: "YOGURTLAND SJSU" },
  { code: "CA286", name: "YOGURTLAND BAKERSFIELD RIVERWALK" },
  { code: "CA285", name: "YOGURTLAND CAPITOLA" },
  { code: "CA284", name: "YOGURTLAND CENTURY CITY MALL" },
  { code: "CA283", name: "YOGURTLAND GARDEN GROVE PLAZA" },
  { code: "CA280", name: "YOGURTLAND MIDTOWN" },
  { code: "CA279", name: "YOGURTLAND CAMP PENDLETON" },
  { code: "CA278", name: "YOGURTLAND AZUSA PLAZA" },
  { code: "CA277", name: "YOGURTLAND MONROVIA" },
  { code: "CA273", name: "YOGURTLAND THE VILLAGE AT ORANGE" },
  { code: "CA269", name: "YOGURTLAND WATSONVILLE" },
  { code: "CA268", name: "YOGURTLAND WILSHIRE & VERMONT" },
  { code: "CA261", name: "YOGURTLAND MIRA LOMA" },
  { code: "CA260", name: "YOGURTLAND SALINAS" },
  { code: "CA258", name: "YOGURTLAND VISALIA" },
  { code: "CA257", name: "YOGURTLAND GARDENA" },
  { code: "CA255", name: "YOGURTLAND SANTA ANA 17TH STREET" },
  { code: "CA254", name: "YOGURTLAND DOWNEY GATEWAY" },
  { code: "CA253", name: "YOGURTLAND GOLETA" },
  { code: "CA252", name: "YOGURTLAND BURBANK VICTORY BLVD." },
  { code: "CA251", name: "YOGURTLAND MORENO VALLEY" },
  { code: "CA250", name: "YOGURTLAND FAIR OAKS" },
  { code: "CA248", name: "YOGURTLAND SAN GABRIEL PROMENADE" },
  { code: "CA247", name: "YOGURTLAND MISSION VIEJO" },
  { code: "CA245", name: "YOGURTLAND LYNWOOD PLAZA MEXICO" },
  { code: "CA244", name: "YOGURTLAND LAGUNA NIGUEL" },
  { code: "CA243", name: "YOGURTLAND SOUTH GATE" },
  { code: "CA242", name: "YOGURTLAND FLOWER HILL DEL MAR" },
  { code: "CA240", name: "YOGURTLAND FREMONT" },
  { code: "CA238", name: "YOGURTLAND FONTANA FALCON RIDGE" },
  { code: "CA237", name: "YOGURTLAND VERMONT & SANTA MONICA BLVD. HOLLYWOOD PLAZA" },
  { code: "CA235", name: "YOGURTLAND VALENCIA CROSSROADS" },
  { code: "CA234", name: "YOGURTLAND PASADENA LAKE AVENUE" },
  { code: "CA233", name: "YOGURTLAND CARSON SOUTHBAY PAVILLION" },
  { code: "CA232", name: "YOGURTLAND SAN DIMAS" },
  { code: "CA231", name: "YOGURTLAND LA VERNE FOOTHILL BLVD" },
  { code: "CA230", name: "YOGURTLAND TERRA VISTA TOWN CENTER" },
  { code: "CA228", name: "YOGURTLAND CAMDEN PARK SAN JOSE" },
  { code: "CA227", name: "YOGURTLAND EDINGER" },
  { code: "CA226", name: "YOGURTLAND CORONA HILLS PLAZA" },
  { code: "CA224", name: "YOGURTLAND GENESEE PLAZA" },
  { code: "CA221", name: "YOGURTLAND YORBA LINDA" },
  { code: "CA220", name: "YOGURTLAND PETALUMA" },
  { code: "CA218", name: "YOGURTLAND POMONA RIO RANCHO TOWN CENTER" },
  { code: "CA217", name: "YOGURTLAND WESTCHESTER" },
  { code: "CA216", name: "YOGURTLAND LA PALMA" },
  { code: "CA215", name: "YOGURTLAND BROKAW COMMONS" },
  { code: "CA212", name: "YOGURTLAND PALMDALE AVENUE P" },
  { code: "CA210", name: "YOGURTLAND PANORAMA CITY" },
  { code: "CA208", name: "YOGURTLAND NORWALK TOWNE SQUARE" },
  { code: "CA206", name: "YOGURTLAND CENTRAL SLAUSON - JUANITA TATE MARKETPLACE" },
  { code: "CA205", name: "YOGURTLAND INGLEWOOD" },
  { code: "CA204", name: "YOGURTLAND STONECREEK VILLAGE" },
  { code: "CA202", name: "YOGURTLAND MOUNTAIN VIEW" },
  { code: "CA201", name: "YOGURTLAND YUCAIPA" },
  { code: "CA200", name: "YOGURTLAND LAKE ELSINORE" },
  { code: "CA195", name: "YOGURTLAND VILLAGE OAKS SAN JOSE" },
  { code: "CA194", name: "YOGURTLAND FONTANA SIERRA AVENUE" },
  { code: "CA193", name: "YOGURTLAND IRVINE SPECTRUM" },
  { code: "CA192", name: "YOGURTLAND PAVILION AT LA QUINTA" },
  { code: "CA188", name: "YOGURTLAND TRUMAN STREET" },
  { code: "CA187", name: "YOGURTLAND THE SHOPS AT MONTEBELLO" },
  { code: "CA186", name: "YOGURTLAND EAGLE ROCK" },
  { code: "CA185", name: "YOGURTLAND BAKER" },
  { code: "CA184", name: "YOGURTLAND PARAMOUNT BLVD" },
  { code: "CA183", name: "YOGURTLAND MENIFEE" },
  { code: "CA181", name: "YOGURTLAND CENTRAL CHINO" },
  { code: "CA179", name: "YOGURTLAND ONTARIO" },
  { code: "CA178", name: "YOGURTLAND ALAMEDA LANDING" },
  { code: "CA177", name: "YOGURTLAND HESPERIA" },
  { code: "CA176", name: "YOGURTLAND WEST COVINA - AZUSA AND AMAR" },
  { code: "CA175", name: "YOGURTLAND COMPTON" },
  { code: "CA173", name: "YOGURTLAND LANCASTER" },
  { code: "CA172", name: "YOGURTLAND LONG BEACH - SPRING ST" },
  { code: "CA170", name: "YOGURTLAND MOUNTAIN GROVE" },
  { code: "CA169", name: "YOGURTLAND WALNUT" },
  { code: "CA168", name: "YOGURTLAND FIVE POINTS PLAZA" },
  { code: "CA167", name: "YOGURTLAND HAYWARD" },
  { code: "CA166", name: "YOGURTLAND GARDEN GROVE PROMENADE" },
  { code: "CA165", name: "YOGURTLAND WILSHIRE & UNION" },
  { code: "CA164", name: "YOGURTLAND BIXBY KNOLLS" },
  { code: "CA163", name: "YOGURTLAND TYLER RIVERSIDE" },
  { code: "CA161", name: "YOGURTLAND DESOTO & NORDHOFF" },
  { code: "CA159", name: "YOGURTLAND SANTA ANA- BRISTOL & SUNFLOWER" },
  { code: "CA158", name: "YOGURTLAND HUNTINGTON PARK" },
  { code: "CA157", name: "YOGURTLAND WEST HOLLYWOOD" },
  { code: "CA153", name: "YOGURTLAND NORTH HOLLYWOOD" },
  { code: "CA151", name: "YOGURTLAND BALDWIN HILLS" },
  { code: "CA148", name: "YOGURTLAND PERRIS MARKET PLACE" },
  { code: "CA147", name: "YOGURTLAND TUSTIN LEGACY" },
  { code: "CA146", name: "YOGURTLAND WOODBRIDGE" },
  { code: "CA145", name: "YOGURTLAND LA HABRA TOWN CENTER" },
  { code: "CA142", name: "YOGURTLAND APPLE VALLEY" },
  { code: "CA141", name: "YOGURTLAND SALTON CITY TRAVEL PLAZA" },
  { code: "CA137", name: "YOGURTLAND RIALTO" },
  { code: "CA136", name: "YOGURTLAND RANCHO MISSION VIEJO" },
  { code: "CA133", name: "YOGURTLAND ANAHEIM - KATELLA" },
  { code: "CA132", name: "YOGURTLAND ROWLAND HEIGHTS - COLIMA & FAIRWAY" },
  { code: "CA131", name: "YOGURTLAND HANFORD" },
  { code: "CA130", name: "YOGURTLAND BELMONT SHORE" },
  { code: "CA129", name: "YOGURTLAND FRESNO - EL PASEO" },
  { code: "CA128", name: "YOGURTLAND EAST PALMDALE - AVE S" },
  { code: "CA125", name: "YOGURTLAND SAN BERNARDINO" },
  { code: "CA123", name: "YOGURTLAND SAN CLEMENTE" },
  { code: "CA120", name: "Yogurtland Pasadena" },
  { code: "CA119", name: "YOGURTLAND RIVERSIDE" },
  { code: "CA118", name: "YOGURTLAND SANTA MONICA PROMENADE" },
  { code: "CA117", name: "Yogurtland-Beaumont" },
  { code: "CA115", name: "YOGURTLAND CHERRYWOOD SQUARE" },
  { code: "CA112", name: "YOGURTLAND 5TH & GRANT" },
  { code: "CA111", name: "YOGURTLAND GOVERNOR'S PLAZA" },
  { code: "CA110", name: "YOGURTLAND NORTHRIDGE CENTER" },
  { code: "CA109", name: "YOGURTLAND TOWNE CTR BATON ROUGE" },
  { code: "CA108", name: "YOGURTLAND SOUTHGATE AT LSU" },
  { code: "CA106", name: "YOGURTLAND LAFAYETTE" },
  { code: "CA105", name: "YOGURTLAND NEW ORLEANS" },
  { code: "CO104", name: "YOGURTLAND HAMILTON" },
  { code: "CO103", name: "Yogurtland West Berlin" },
  { code: "CO102", name: "YOGURTLAND LAS VEGAS TOWN SQUARE" },
  { code: "CO101", name: "YOGURTLAND WEST FLAMINGO" },
  { code: "LA104", name: "YOGURTLAND 215 & EASTERN" },
  { code: "LA103", name: "YOGURTLAND CENTENNIAL GATEWAY" },
  { code: "LA102", name: "YOGURTLAND WEST LAKE MEAD" },
  { code: "LA101", name: "YOGURTLAND HENDERSON STEPHANIE STREET" },
  { code: "NJ110", name: "YOGURTLAND WINTERWOOD" },
  { code: "NJ109", name: "YOGURTLAND 215 & N DECATUR" },
  { code: "NV113", name: "YOGURTLAND 215 & RAINBOW" },
  { code: "NV112", name: "YOGURTLAND LAS VEGAS FASHION SHOW FOOD COURT" },
  { code: "NV111", name: "YOGURTLAND Las Vegas - Boca Park" },
  { code: "NV110", name: "Yogurtland Las Vegas" },
  { code: "NV109", name: "Yogurtland Demo Vendor" },
  { code: "NV108", name: "YOGURTLAND CARROLLTON" },
  { code: "NV107", name: "YOGURTLAND SOUTHLAKE DFW" },
  { code: "NV105", name: "YOGURTLAND DALLAS NORTHWEST HWY" },
  { code: "NV104", name: "YOGURTLAND MONTGOMERY PLAZA" },
  { code: "NV103", name: "YOGURTLAND GARLAND FIREWHEEL TOWN CTR" },
  { code: "NV102", name: "YOGURTLAND MEMORIAL CITY MALL" },
  { code: "NV101", name: "YOGURTLAND FAIRFIELD TOWN CENTER" },
  { code: "TX128", name: "YOGURTLAND LAKE HIGHLANDS TOWN CENTER" },
  { code: "TX126", name: "YOGURTLAND WESTCHASE" },
  { code: "TX124", name: "YOGURTLAND FT. WORTH- WATERSIDE" },
  { code: "TX123", name: "YOGURTLAND PLANO" },
  { code: "TX120", name: "YOGURTLAND DALLAS - LAKEWOOD" },
  { code: "TX119", name: "YOGURTLAND SUGAR LAND" },
  { code: "TX117", name: "YOGURTLAND JORDAN LANDING" },
  { code: "TX111", name: "YOGURTLAND OREM" },
  { code: "TX109", name: "YOGURTLAND RED ROCK COMMONS" },
  { code: "TX105", name: "YOGURTLAND" },
];
